const $=selector=>document.querySelector(selector);
let project={name:'Mi proyecto',objective:'Resolver una necesidad concreta de sus usuarios.',stakeholder:'Usuario final'};
let requirements=[];
const typeInfo={functional:{prefix:'RF',label:'Requisito funcional'},nonfunctional:{prefix:'RNF',label:'Requisito no funcional'},story:{prefix:'HU',label:'Historia de usuario'}};
const priorityInfo={Must:{label:'Must',color:'#ffb0a1'},Should:{label:'Should',color:'#ffdc83'},Could:{label:'Could',color:'#a9ddc8'},"Won't":{label:"Won't",color:'#c7cbd3'}};
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function nextId(type){const prefix=typeInfo[type].prefix;let number=1;while(requirements.some(item=>item.id===`${prefix}-${String(number).padStart(2,'0')}`))number++;return `${prefix}-${String(number).padStart(2,'0')}`;}
function render(){const counts=Object.fromEntries(Object.keys(priorityInfo).map(key=>[key,requirements.filter(item=>item.priority===key).length]));$('#moscowSummary').innerHTML=Object.entries(priorityInfo).map(([key,info])=>`<span style="--priority:${info.color}"><b>${info.label}</b><strong>${counts[key]}</strong></span>`).join('');$('#requirementCount').textContent=`${requirements.length} ${requirements.length===1?'elemento':'elementos'}`;$('#requirementList').innerHTML=requirements.length?requirements.map(item=>`<article class="requirement-card"><div class="requirement-top"><span class="id-chip">${item.id}</span><span class="priority-chip" style="--priority:${priorityInfo[item.priority].color}">${item.priority}</span><button class="remove" data-id="${item.id}" aria-label="Eliminar ${item.id}">×</button></div><h4>${typeInfo[item.type].label}</h4><p>${escapeHtml(item.description)}</p><dl><div><dt>Aceptación</dt><dd>${escapeHtml(item.acceptance)}</dd></div><div><dt>Verificación</dt><dd>${escapeHtml(item.verification)}</dd></div><div><dt>Fuente</dt><dd>${escapeHtml(item.source)}</dd></div></dl></article>`).join(''):'<p class="empty-list">Agrega requisitos para construir el documento.</p>';$('#documentPreview').innerHTML=`<header><p>ESRE · Versión 0.1</p><h3>${escapeHtml(project.name)}</h3><span>Parte interesada: ${escapeHtml(project.stakeholder)}</span></header><section><h4>1. Propósito y alcance</h4><p>${escapeHtml(project.objective)}</p></section><section><h4>2. Requisitos y trazabilidad</h4>${requirements.length?requirements.map(item=>`<article class="preview-item"><div><b>${item.id}</b><span>${typeInfo[item.type].label} · ${item.priority}</span></div><p>${escapeHtml(item.description)}</p><small><b>Criterio de aceptación:</b> ${escapeHtml(item.acceptance)}<br><b>Verificación:</b> ${escapeHtml(item.verification)} · <b>Fuente:</b> ${escapeHtml(item.source)}</small></article>`).join(''):'<p class="muted">Aún no se registraron requisitos.</p>'}</section><section><h4>3. Resumen MoSCoW</h4><p>Must: ${counts.Must} · Should: ${counts.Should} · Could: ${counts.Could} · Won't: ${counts["Won't"]}</p></section>`;}
$('#projectForm').addEventListener('submit',event=>{event.preventDefault();project={name:$('#projectName').value.trim()||'Proyecto sin nombre',objective:$('#projectObjective').value.trim()||'Sin objetivo definido.',stakeholder:$('#stakeholder').value.trim()||'Sin especificar'};render();});
$('#requirementForm').addEventListener('submit',event=>{event.preventDefault();const type=$('#requirementType').value,description=$('#description').value.trim(),acceptance=$('#acceptance').value.trim();if(!description||!acceptance)return;requirements.push({id:nextId(type),type,priority:$('#priority').value,description,acceptance,verification:$('#verification').value,source:$('#source').value.trim()||'Sin especificar'});$('#description').value='';$('#acceptance').value='';render();});
$('#requirementList').addEventListener('click',event=>{const button=event.target.closest('.remove');if(!button)return;requirements=requirements.filter(item=>item.id!==button.dataset.id);render();});
$('#exampleBtn').addEventListener('click',()=>{project={name:'Plataforma de reservas',objective:'Permitir que clientes consulten y reserven turnos desde la web.',stakeholder:'Área de atención al cliente'};$('#projectName').value=project.name;$('#projectObjective').value=project.objective;$('#stakeholder').value=project.stakeholder;requirements=[{id:'RF-01',type:'functional',priority:'Must',description:'El sistema deberá permitir que un cliente consulte los turnos disponibles.',acceptance:'Dado un servicio seleccionado, cuando el cliente consulte disponibilidad, entonces verá fechas y horarios libres.',verification:'Prueba',source:'Área de atención al cliente'},{id:'HU-01',type:'story',priority:'Should',description:'Como cliente, quiero cancelar una reserva para liberar el turno si no puedo asistir.',acceptance:'Dada una reserva vigente, cuando el cliente la cancele, entonces el horario volverá a estar disponible.',verification:'Demostración',source:'Usuario final'},{id:'RNF-01',type:'nonfunctional',priority:'Must',description:'La consulta de disponibilidad deberá responder en menos de dos segundos.',acceptance:'En una prueba con 50 consultas simultáneas, el 95% de las respuestas será menor a dos segundos.',verification:'Prueba',source:'Equipo técnico'}];render();});
$('#printBtn').addEventListener('click',()=>window.print());function setTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=theme;$('#themeToggle').setAttribute('aria-checked',String(dark));$('.theme-label').textContent=dark?'Modo claro':'Modo oscuro';$('.theme-knob').textContent=dark?'☾':'☼';localStorage.setItem('esre-theme',theme);}$('#themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));setTheme(localStorage.getItem('esre-theme')||'light');render();
