const colors=['#ffb387','#ffe084','#94cdf5','#94dfc6','#bbb0f6','#f4a8bb'];
let files=[{id:1,name:'informe.pdf',blocks:4},{id:2,name:'datos.csv',blocks:6},{id:3,name:'foto.png',blocks:3},{id:4,name:'video.mp4',blocks:8}];
let algorithm='contiguous';
const $=selector=>document.querySelector(selector);
const names={contiguous:'CONTIGUA · Bloques consecutivos',linked:'ENLAZADA · Bloques conectados',indexed:'INDEXADA · Un bloque índice por archivo'};
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function renderList(){ $('#fileList').innerHTML=files.length?files.map((file,index)=>`<div class="file-item"><span class="file-chip" style="--color:${colors[index%colors.length]}">${escapeHtml(file.name)}</span><span>${file.blocks}</span><button class="remove" data-id="${file.id}" aria-label="Eliminar archivo">×</button></div>`).join(''):'<p class="empty-list">Sin archivos.</p>';}
function takeScattered(free,count,seed){const chosen=[];let cursor=seed%Math.max(free.length,1);while(chosen.length<count&&free.length){cursor%=free.length;chosen.push(free.splice(cursor,1)[0]);cursor+=2;}return chosen;}
function allocate(){const total=Math.max(8,Math.min(120,Number($('#diskBlocks').value)||8));const free=Array.from({length:total},(_,index)=>index);const results=[];for(const file of files){let data=[],indexBlock=null;if(algorithm==='contiguous'){for(let start=0;start<=free.length-file.blocks;start++){const segment=free.slice(start,start+file.blocks);if(segment.every((block,i)=>i===0||block===segment[i-1]+1)){data=free.splice(start,file.blocks);break;}}}else if(algorithm==='linked'){if(free.length>=file.blocks)data=takeScattered(free,file.blocks,file.id*3);}else if(free.length>=file.blocks+1){indexBlock=takeScattered(free,1,file.id)[0];data=takeScattered(free,file.blocks,file.id*5);}results.push({...file,data,indexBlock,stored:data.length===file.blocks});}renderResults(total,results,free);}
function renderResults(total,results,free){const cellData=Array.from({length:total},()=>null);results.forEach((result,fileIndex)=>{if(!result.stored)return;result.data.forEach(block=>cellData[block]={file:result,index:false,color:colors[fileIndex%colors.length]});if(result.indexBlock!==null)cellData[result.indexBlock]={file:result,index:true,color:colors[fileIndex%colors.length]};});const used=cellData.filter(Boolean).length;const fragments=free.reduce((count,block,index)=>count+(index===0||block!==free[index-1]+1?1:0),0);const stored=results.filter(result=>result.stored).length;$('#emptyState').hidden=true;$('#results').hidden=false;$('#diskSummary').textContent=`${total} bloques de disco`;$('#usedBlocks').textContent=used;$('#freeBlocks').textContent=total-used;$('#storedFiles').textContent=`${stored}/${results.length}`;$('#freeFragments').textContent=fragments;$('#diskMap').innerHTML=cellData.map((cell,index)=>cell?`<div class="disk-cell used ${cell.index?'index-cell':''}" title="${escapeHtml(cell.file.name)} · bloque ${index}" style="--file-color:${cell.color}"><span>${cell.index?'I':cell.file.name.slice(0,2)}</span><small>${index}</small></div>`:`<div class="disk-cell" title="Bloque ${index} libre"><span>·</span><small>${index}</small></div>`).join('');$('#resultsBody').innerHTML=results.map(result=>result.stored?`<tr><td>${escapeHtml(result.name)}</td><td>${result.blocks}</td><td>${result.data.join(', ')}</td><td>${result.indexBlock===null?'—':result.indexBlock}</td><td><span class="status success">Guardado</span></td></tr>`:`<tr><td>${escapeHtml(result.name)}</td><td>${result.blocks}</td><td>—</td><td>—</td><td><span class="status failed">Sin espacio</span></td></tr>`).join('');}
function resetResults(){$('#results').hidden=true;$('#emptyState').hidden=false;}
$('#fileForm').addEventListener('submit',event=>{event.preventDefault();const name=$('#fileName').value.trim()||`archivo-${files.length+1}`,blocks=Number($('#fileBlocks').value);if(blocks<1||!Number.isFinite(blocks))return;files.push({id:Date.now(),name,blocks});$('#fileName').value=`archivo-${files.length+1}`;$('#fileBlocks').value=1;renderList();resetResults();});
$('#fileList').addEventListener('click',event=>{const button=event.target.closest('.remove');if(!button)return;files=files.filter(file=>file.id!==Number(button.dataset.id));renderList();resetResults();});
$('#clearBtn').addEventListener('click',()=>{files=[];renderList();resetResults();});
$('#exampleBtn').addEventListener('click',()=>{files=[{id:1,name:'informe.pdf',blocks:4},{id:2,name:'datos.csv',blocks:6},{id:3,name:'foto.png',blocks:3},{id:4,name:'video.mp4',blocks:8}];renderList();resetResults();});
$('#diskBlocks').addEventListener('change',resetResults);document.querySelectorAll('.algorithm-tab').forEach(button=>button.addEventListener('click',()=>{algorithm=button.dataset.algorithm;document.querySelectorAll('.algorithm-tab').forEach(item=>item.classList.toggle('active',item===button));$('#algorithmBadge').textContent=names[algorithm];}));
function setTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=theme;$('#themeToggle').setAttribute('aria-checked',String(dark));$('.theme-label').textContent=dark?'Modo claro':'Modo oscuro';$('.theme-knob').textContent=dark?'☾':'☼';localStorage.setItem('chrismuladores-theme',theme);}
$('#themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));setTheme(localStorage.getItem('chrismuladores-theme')||'light');$('#simulateBtn').addEventListener('click',allocate);renderList();
