const $=selector=>document.querySelector(selector);
const techniques={
  'Entrevista':{kind:'Conversacional',description:'Diálogo planificado, individual o grupal, con preguntas abiertas y cerradas.',best:'Profundizar objetivos, excepciones, decisiones y temas sensibles.',advantage:'Permite repreguntar y descubrir información inesperada.',limit:'Consume tiempo y puede introducir sesgos del entrevistador.',output:'Notas, transcripción y necesidades candidatas.'},
  'Encuesta':{kind:'Cuantitativa',description:'Cuestionario uniforme distribuido a una población amplia.',best:'Medir preferencias, frecuencia, satisfacción o validar hipótesis.',advantage:'Alcanza muchas personas y facilita comparar respuestas.',limit:'Ofrece poca profundidad y depende de preguntas bien redactadas.',output:'Datos tabulados, tendencias y segmentos.'},
  'Observación':{kind:'Contextual',description:'Estudio del trabajo real en su ambiente, de forma directa o participante.',best:'Revelar conocimiento tácito, atajos, interrupciones y diferencias entre proceso formal y real.',advantage:'Aporta evidencia del comportamiento y del contexto.',limit:'Puede alterar la conducta y requiere tiempo para interpretar lo observado.',output:'Registro de tareas, eventos, problemas y oportunidades.'},
  'Taller colaborativo':{kind:'Colaborativa',description:'Sesión facilitada donde las partes interesadas modelan, priorizan y acuerdan requisitos en conjunto.',best:'Resolver conflictos, construir visión compartida y tomar decisiones rápidas.',advantage:'Genera consenso y reduce ciclos de revisión.',limit:'Necesita buena facilitación, agenda y participantes con autoridad.',output:'Modelos, acuerdos, prioridades y decisiones.'},
  'Análisis documental':{kind:'Analítica',description:'Revisión de normas, formularios, manuales, contratos, reportes y sistemas existentes.',best:'Comprender terminología, reglas, restricciones y antecedentes antes de consultar.',advantage:'Es trazable y aprovecha conocimiento ya registrado.',limit:'Los documentos pueden estar desactualizados o no reflejar la práctica.',output:'Glosario, reglas, fuentes y preguntas pendientes.'},
  'Prototipado':{kind:'Experimental',description:'Representación de baja o alta fidelidad utilizada para obtener retroalimentación concreta.',best:'Validar flujos, interfaces y necesidades difíciles de expresar.',advantage:'Reduce ambigüedad y hace visible una solución posible.',limit:'Puede sesgar hacia el diseño o confundirse con producto terminado.',output:'Feedback, decisiones de interfaz y criterios de aceptación.'},
  'Grupo focal':{kind:'Exploratoria',description:'Discusión moderada con un grupo representativo sobre experiencias y expectativas.',best:'Explorar percepciones, lenguaje y diversidad de opiniones.',advantage:'La interacción genera ideas que no aparecen individualmente.',limit:'Las voces dominantes pueden condicionar al grupo.',output:'Temas, percepciones, acuerdos y divergencias.'}
};
function scores(){const v={objective:$('#objective').value,audience:$('#audience').value,availability:$('#availability').value,knowledge:$('#knowledge').value,sensitivity:$('#sensitivity').value};const s=Object.fromEntries(Object.keys(techniques).map(name=>[name,0]));if(v.objective==='explore'){s.Entrevista+=4;s['Grupo focal']+=3;s.Prototipado+=2}if(v.objective==='validate'){s['Taller colaborativo']+=4;s.Prototipado+=3;s.Encuesta+=2}if(v.objective==='measure')s.Encuesta+=6;if(v.objective==='process'){s.Observación+=6;s['Análisis documental']+=3}if(v.audience==='many'){s.Encuesta+=4;s['Grupo focal']+=2}else{s.Entrevista+=3;s['Taller colaborativo']+=2}if(v.availability==='low'){s.Encuesta+=2;s['Análisis documental']+=4}else{s.Entrevista+=2;s['Taller colaborativo']+=2;s.Observación+=2}if(v.knowledge==='explicit')s['Análisis documental']+=5;if(v.knowledge==='tacit'){s.Observación+=5;s.Entrevista+=2}if(v.knowledge==='conflict'){s['Taller colaborativo']+=5;s['Grupo focal']+=2}if(v.sensitivity==='sensitive'){s.Entrevista+=4;s.Encuesta+=2;s['Taller colaborativo']-=2;s['Grupo focal']-=2}return s}
function analyze(){const ordered=Object.entries(scores()).sort((a,b)=>b[1]-a[1]);const top=ordered.slice(0,3);$('#resultTitle').textContent=`Técnica principal: ${top[0][0]}`;$('#resultText').textContent=`${techniques[top[0][0]].best} La puntuación orienta la elección: debe confirmarse con tiempo, acceso y riesgos reales.`;$('#ranking').innerHTML=top.map(([name,score],index)=>`<article class="rank ${index===0?'selected':''}"><span>0${index+1}</span><div><h3>${name}</h3><p>${techniques[name].description}</p></div><b>${score} pts</b></article>`).join('');$('#plan').innerHTML=`<h3>Plan combinado sugerido</h3><ol><li><b>Preparar:</b> revisa documentos y define objetivos, participantes y preguntas.</li><li><b>Descubrir con ${top[0][0]}:</b> registra hechos, necesidades, supuestos y dudas.</li><li><b>Contrastar con ${top[1][0]}:</b> busca diferencias y evidencia complementaria.</li><li><b>Validar con ${top[2][0]}:</b> confirma conclusiones y conserva trazabilidad hacia la fuente.</li></ol>`}
$('#catalog').innerHTML=Object.entries(techniques).map(([name,item])=>`<article><span>${item.kind}</span><h3>${name}</h3><p>${item.description}</p><dl><div><dt>Conviene para</dt><dd>${item.best}</dd></div><div><dt>Ventaja</dt><dd>${item.advantage}</dd></div><div><dt>Limitación</dt><dd>${item.limit}</dd></div><div><dt>Producto</dt><dd>${item.output}</dd></div></dl></article>`).join('');
$('#contextForm').addEventListener('submit',event=>{event.preventDefault();analyze()});$('#exampleBtn').addEventListener('click',()=>{$('#objective').value='process';$('#audience').value='few';$('#availability').value='high';$('#knowledge').value='tacit';$('#sensitivity').value='normal';analyze()});function setTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=theme;$('#themeToggle').setAttribute('aria-checked',String(dark));$('.theme-label').textContent=dark?'Modo claro':'Modo oscuro';$('.theme-knob').textContent=dark?'☾':'☼';localStorage.setItem('chrismuladores-theme',theme)}$('#themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));setTheme(localStorage.getItem('chrismuladores-theme')||'dark');analyze();
