const $ = selector => document.querySelector(selector);
const systemTypes = {
  batch:{name:'Sistema por lotes',short:'Por lotes',icon:'▤',color:'#ffb387',response:'Baja',throughput:'Muy alto',predictability:'Media',best:'Procesamiento repetitivo y grandes volúmenes sin interacción inmediata.',risk:'No es apropiado cuando una persona espera respuesta en el momento.',copy:'Agrupa trabajos similares y los ejecuta de forma secuencial, maximizando el uso de recursos.'},
  timesharing:{name:'Sistema de tiempo compartido',short:'Tiempo compartido',icon:'◌',color:'#94cdf5',response:'Alta',throughput:'Medio',predictability:'Media',best:'Aulas, servidores multiusuario y aplicaciones de uso simultáneo.',risk:'La sobrecarga de alternar entre tareas puede reducir el rendimiento total.',copy:'Distribuye el procesador entre varios usuarios para que cada uno reciba respuesta frecuente.'},
  realtime:{name:'Sistema de tiempo real',short:'Tiempo real',icon:'◷',color:'#ffcf70',response:'Muy alta',throughput:'Medio',predictability:'Muy alta',best:'Control industrial, dispositivos médicos y tareas con plazos estrictos.',risk:'Requiere planificación cuidadosa; fallar un plazo puede ser crítico.',copy:'Prioriza que las tareas se completen dentro de límites de tiempo definidos y verificables.'},
  distributed:{name:'Sistema distribuido',short:'Distribuido',icon:'◈',color:'#a99af4',response:'Media',throughput:'Alta',predictability:'Media',best:'Clusters, servicios repartidos y cargas que necesitan varios equipos.',risk:'Depende de la red y agrega complejidad de coordinación.',copy:'Coordina recursos de múltiples computadoras para que funcionen como un conjunto.'},
  embedded:{name:'Sistema embebido',short:'Embebido',icon:'◉',color:'#75d7b8',response:'Alta',throughput:'Bajo',predictability:'Alta',best:'Electrodomésticos, sensores y dispositivos con memoria o energía limitada.',risk:'Está diseñado para una función concreta y tiene poca flexibilidad.',copy:'Se integra a un dispositivo específico y optimiza al máximo sus recursos limitados.'}
};
let selectedType='timesharing';
function renderTypes(){ $('#typeGrid').innerHTML=Object.entries(systemTypes).map(([key,type])=>`<button class="type-card ${key===selectedType?'selected':''}" data-type="${key}" type="button" style="--type-color:${type.color}"><span>${type.icon}</span><b>${type.short}</b><small>${type.best}</small></button>`).join('');renderDetail();}
function renderDetail(){const type=systemTypes[selectedType];$('#typeDetail').innerHTML=`<div class="detail-marker" style="background:${type.color}">${type.icon}</div><div><p class="section-label">${type.short}</p><h3>${type.name}</h3><p>${type.copy}</p></div><dl><div><dt>Ideal para</dt><dd>${type.best}</dd></div><div><dt>Atención</dt><dd>${type.risk}</dd></div></dl>`;}
function recommendation(){const workload=$('#workload').value,deadline=Number($('#deadline').value),limited=$('#limitedHardware').checked,users=Number($('#users').value);if(workload==='control'||deadline>=8)return'realtime';if(limited)return'embedded';if(workload==='distributed')return'distributed';if(workload==='batch')return'batch';return users>=1?'timesharing':'batch';}
function analyze(){const key=recommendation(),type=systemTypes[key];selectedType=key;$('#recommendationBadge').textContent=type.short;$('#recommendationBadge').style.background=type.color;$('#recommendationIcon').textContent=type.icon;$('#recommendationIcon').style.background=type.color;$('#recommendationTitle').textContent=type.name;$('#recommendationCopy').textContent=type.copy;$('#responseMetric').textContent=type.response;$('#throughputMetric').textContent=type.throughput;$('#predictabilityMetric').textContent=type.predictability;renderTypes();}
function updateRange(){ $('#usersValue').textContent=$('#users').value;$('#deadlineValue').textContent=$('#deadline').value; }
const scenarios={office:{workload:'interactive',users:35,deadline:4,limited:false},robot:{workload:'control',users:1,deadline:10,limited:true},cluster:{workload:'distributed',users:8,deadline:5,limited:false}};
$('#scenarioForm').addEventListener('submit',event=>{event.preventDefault();analyze();});
$('#users').addEventListener('input',updateRange);$('#deadline').addEventListener('input',updateRange);
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{const scenario=scenarios[button.dataset.scenario];$('#workload').value=scenario.workload;$('#users').value=scenario.users;$('#deadline').value=scenario.deadline;$('#limitedHardware').checked=scenario.limited;updateRange();analyze();}));
$('#typeGrid').addEventListener('click',event=>{const card=event.target.closest('[data-type]');if(!card)return;selectedType=card.dataset.type;renderTypes();});
function setTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=theme;$('#themeToggle').setAttribute('aria-checked',String(dark));$('.theme-label').textContent=dark?'Modo claro':'Modo oscuro';$('.theme-knob').textContent=dark?'☾':'☼';localStorage.setItem('chrismuladores-theme',theme);}
$('#themeToggle').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));setTheme(localStorage.getItem('chrismuladores-theme')||'dark');updateRange();analyze();
